/**
 * Copyright (c) 2026 Data In Motion and others.
 * All rights reserved.
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     Data In Motion - initial API and implementation
 */
package org.example.spi.core;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.net.MalformedURLException;
import java.net.URI;
import java.net.URL;
import java.net.URLConnection;
import java.net.URLStreamHandler;
import java.nio.charset.StandardCharsets;
import java.util.List;

import org.osgi.framework.Bundle;

/**
 * Fallback for providers that exist only in module-info ({@code provides}) and
 * therefore have no META-INF/services file to hand out: synthetic
 * {@code spi:/<serviceName>/<bundleId>} URLs whose content is a generated
 * META-INF/services file for one bundle. Created with
 * {@link URL#of(URI, URLStreamHandler)}, so no global URLStreamHandlerFactory
 * is touched. Providers read from real files are served by their bundle entry
 * URLs, see {@link SpiRegistry#serviceResources}.
 */
final class SpiUrlHandler extends URLStreamHandler {

	private final SpiRegistry registry;

	SpiUrlHandler(SpiRegistry registry) {
		this.registry = registry;
	}

	URL url(String serviceName, Bundle bundle) {
		try {
			return URL.of(URI.create("spi:/" + serviceName + "/" + bundle.getBundleId()), this);
		} catch (MalformedURLException e) {
			throw new IllegalStateException(e);
		}
	}

	@Override
	protected URLConnection openConnection(URL url) throws IOException {
		String path = url.getPath(); // /serviceName/bundleId
		int slash = path.lastIndexOf('/');
		String serviceName = path.substring(1, slash);
		long bundleId = Long.parseLong(path.substring(slash + 1));
		StringBuilder content = new StringBuilder("# generated by spi.mediator\n");
		List<ProviderEntry> entries = registry.providers(serviceName, null);
		for (ProviderEntry entry : entries) {
			if (entry.bundle().getBundleId() == bundleId) {
				content.append(entry.implName()).append('\n');
			}
		}
		byte[] bytes = content.toString().getBytes(StandardCharsets.UTF_8);
		return new URLConnection(url) {
			@Override
			public void connect() {
			}

			@Override
			public InputStream getInputStream() {
				return new ByteArrayInputStream(bytes);
			}
		};
	}
}
